# Generated by Django 2.2.2 on 2019-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='company',
            name='name_of_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
