# Generated by Django 2.2.2 on 2019-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190612_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(default='1-9', max_length=7),
        ),
    ]
