# Generated by Django 2.2.2 on 2019-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20190612_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('1-9', '1-9'), ('10-49', '10-49'), ('50-99', '50-99'), ('99-999', '99-999'), ('1000+', '1000+')], default='1-9', max_length=7),
        ),
    ]
